name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  verify-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify files
        run: echo "Proyecto HTML/CSS/JS verificado correctamente"

      - name: Deploy simulation
        run: echo "Pipeline ejecutado con éxito"